#!/usr/bin/env python

import os.path
import sys

from types import ModuleType
from types import FunctionType
from types import ClassType

SYNDOC = "Syndoc"
print "[N]: [%s] Initilizing..." % SYNDOC

toDocument = [
	"./Syn/",
]

def fetchDocs(path):
	folder = os.path.abspath(path)
	print folder

	ret = {}

	sys.path.append(folder)
	to_import = [f for f in os.listdir(folder) if not f.endswith(".pyc")]
	for mod in to_import:
	        if mod.endswith(".py"):
	                name = mod [:-3]
	                mod = __import__(name)
			funs = mod.__dict__
			for x in funs:
				if isinstance(funs[x], FunctionType):
					try:
						ret[mod.__name__].append(x)
					except KeyError as e:
						ret[mod.__name__] = [x]
				if isinstance(funs[x], ClassType):
					try:
						ret[mod.__name__].append(x)
					except KeyError as e:
						ret[mod.__name__] = [x]
	return ret

for n in toDocument:
	print fetchDocs(n)
