#!/usr/bin/env python

import os.path
import sys

from types import ModuleType
from types import FunctionType
from types import ClassType

SYNDOC = "Syndoc"
print "[N]: [%s] Initilizing..." % SYNDOC

toDocument = [
	"./Syn/",
]

def fetchDocs(path):
	folder = os.path.abspath(path)
	print folder

	sys.path.append(folder)
	to_import = [f for f in os.listdir(folder) if not f.endswith(".pyc")]
	for mod in to_import:
	        if mod.endswith(".py"):
	                name = mod [:-3]
	                mod = __import__(name)
			funs = mod.__dict__
			for x in funs:
				if isinstance(funs[x], FunctionType):
					print "New fn: %s / %s" % ( mod.__name__, x )

for n in toDocument:
	fetchDocs(n)
